# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: benyblack.ntilde
PackageVersion: 0.11.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: Ntilde.exe
  PortableCommandAlias: ntilde
UpgradeBehavior: uninstallPrevious
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/benyblack/ntilde/releases/download/v0.11.0/ntilde-win-x64-v0.11.0.zip
  InstallerSha256: A11280706D4B8D248D706EE18AD30D6C2F59CA75CEEC4FDE422C23B0177D761E
ManifestType: installer
ManifestVersion: 1.10.0
